# Generated by Django 5.1.5 on 2025-01-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('edad', models.IntegerField()),
                ('altura', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
